apiVersion: v1
kind: Service
metadata:
  name: alpaca-auth-api
  labels:
    app: alpaca-auth
    tier: api
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: alpaca-auth
    tier: api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca-auth-api
  labels:
    app: alpaca-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpaca-auth
      tier: api
  template:
    metadata:
      labels:
        app: alpaca-auth
        tier: api
    spec:
      containers:
      - image: hanakoa/alpaca-auth-api:v0.0.1
        name: alpaca-auth-api
        env:
        - name: DB_HOST
          value: alpaca-auth-db
        - name: DB_DATABASE
          value: alpaca_auth
        - name: DB_USER
          value: alpaca
        - name: DB_PASSWORD
          value: password
        - name: RABBITMQ_USER
          value: guest
        - name: RABBITMQ_PASSWORD
          value: guest
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: ALPACA_SECRET
          value: 4FFFA6A10E744158464EB55133A475673264748804882A1B4F8106D545C584EF
        - name: ORIGIN_ALLOWED
          value: http://localhost:8080
        ports:
        - containerPort: 8080
