// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/mfa.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	pb/mfa.proto

It has these top-level messages:
	Send2FACodeRequest
	Send2FACodeResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Send2FACodeRequest struct {
	ResetCode string `protobuf:"bytes,1,opt,name=resetCode" json:"resetCode,omitempty"`
	PersonId  int64  `protobuf:"varint,2,opt,name=personId" json:"personId,omitempty"`
}

func (m *Send2FACodeRequest) Reset()                    { *m = Send2FACodeRequest{} }
func (m *Send2FACodeRequest) String() string            { return proto1.CompactTextString(m) }
func (*Send2FACodeRequest) ProtoMessage()               {}
func (*Send2FACodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Send2FACodeRequest) GetResetCode() string {
	if m != nil {
		return m.ResetCode
	}
	return ""
}

func (m *Send2FACodeRequest) GetPersonId() int64 {
	if m != nil {
		return m.PersonId
	}
	return 0
}

type Send2FACodeResponse struct {
	ResetCode string `protobuf:"bytes,1,opt,name=resetCode" json:"resetCode,omitempty"`
	PersonId  int64  `protobuf:"varint,2,opt,name=personId" json:"personId,omitempty"`
}

func (m *Send2FACodeResponse) Reset()                    { *m = Send2FACodeResponse{} }
func (m *Send2FACodeResponse) String() string            { return proto1.CompactTextString(m) }
func (*Send2FACodeResponse) ProtoMessage()               {}
func (*Send2FACodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Send2FACodeResponse) GetResetCode() string {
	if m != nil {
		return m.ResetCode
	}
	return ""
}

func (m *Send2FACodeResponse) GetPersonId() int64 {
	if m != nil {
		return m.PersonId
	}
	return 0
}

func init() {
	proto1.RegisterType((*Send2FACodeRequest)(nil), "proto.Send2FACodeRequest")
	proto1.RegisterType((*Send2FACodeResponse)(nil), "proto.Send2FACodeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Send2FACodeService service

type Send2FACodeServiceClient interface {
	Send2FACode(ctx context.Context, in *Send2FACodeRequest, opts ...grpc.CallOption) (*Send2FACodeResponse, error)
}

type send2FACodeServiceClient struct {
	cc *grpc.ClientConn
}

func NewSend2FACodeServiceClient(cc *grpc.ClientConn) Send2FACodeServiceClient {
	return &send2FACodeServiceClient{cc}
}

func (c *send2FACodeServiceClient) Send2FACode(ctx context.Context, in *Send2FACodeRequest, opts ...grpc.CallOption) (*Send2FACodeResponse, error) {
	out := new(Send2FACodeResponse)
	err := grpc.Invoke(ctx, "/proto.Send2FACodeService/Send2FACode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Send2FACodeService service

type Send2FACodeServiceServer interface {
	Send2FACode(context.Context, *Send2FACodeRequest) (*Send2FACodeResponse, error)
}

func RegisterSend2FACodeServiceServer(s *grpc.Server, srv Send2FACodeServiceServer) {
	s.RegisterService(&_Send2FACodeService_serviceDesc, srv)
}

func _Send2FACodeService_Send2FACode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Send2FACodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Send2FACodeServiceServer).Send2FACode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Send2FACodeService/Send2FACode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Send2FACodeServiceServer).Send2FACode(ctx, req.(*Send2FACodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Send2FACodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Send2FACodeService",
	HandlerType: (*Send2FACodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send2FACode",
			Handler:    _Send2FACodeService_Send2FACode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/mfa.proto",
}

func init() { proto1.RegisterFile("pb/mfa.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0xd2, 0xcf,
	0x4d, 0x4b, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x7e, 0x5c, 0x42,
	0xc1, 0xa9, 0x79, 0x29, 0x46, 0x6e, 0x8e, 0xce, 0xf9, 0x29, 0xa9, 0x41, 0xa9, 0x85, 0xa5, 0xa9,
	0xc5, 0x25, 0x42, 0x32, 0x5c, 0x9c, 0x45, 0xa9, 0xc5, 0xa9, 0x25, 0x20, 0x31, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0x84, 0x80, 0x90, 0x14, 0x17, 0x47, 0x41, 0x6a, 0x51, 0x71, 0x7e, 0x9e,
	0x67, 0x8a, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x9c, 0xaf, 0xe4, 0xcf, 0x25, 0x8c, 0x62,
	0x5e, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0x2a, 0xf9, 0x06, 0x1a, 0xc5, 0xa0, 0x38, 0x30, 0x38, 0xb5,
	0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8, 0x8d, 0x8b, 0x1b, 0x49, 0x54, 0x48, 0x12, 0xe2, 0x29, 0x3d,
	0x4c, 0xaf, 0x48, 0x49, 0x61, 0x93, 0x82, 0xb8, 0x4a, 0x89, 0x21, 0x89, 0x0d, 0x2c, 0x69, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xa7, 0xef, 0xb6, 0x1c, 0x01, 0x00, 0x00,
}
