// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/auth.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	pb/auth.proto

It has these top-level messages:
	GetPersonRequest
	GetPersonResponse
	ResetPasswordRequest
	ResetPasswordResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type GetPersonRequest struct {
	EmailAddress string `protobuf:"bytes,1,opt,name=emailAddress" json:"emailAddress,omitempty"`
}

func (m *GetPersonRequest) Reset()                    { *m = GetPersonRequest{} }
func (m *GetPersonRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetPersonRequest) ProtoMessage()               {}
func (*GetPersonRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetPersonRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

type GetPersonResponse struct {
	PersonId int64 `protobuf:"varint,1,opt,name=personId" json:"personId,omitempty"`
}

func (m *GetPersonResponse) Reset()                    { *m = GetPersonResponse{} }
func (m *GetPersonResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetPersonResponse) ProtoMessage()               {}
func (*GetPersonResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetPersonResponse) GetPersonId() int64 {
	if m != nil {
		return m.PersonId
	}
	return 0
}

type ResetPasswordRequest struct {
	PersonId    int64  `protobuf:"varint,1,opt,name=personId" json:"personId,omitempty"`
	NewPassword string `protobuf:"bytes,2,opt,name=newPassword" json:"newPassword,omitempty"`
}

func (m *ResetPasswordRequest) Reset()                    { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string            { return proto1.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()               {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ResetPasswordRequest) GetPersonId() int64 {
	if m != nil {
		return m.PersonId
	}
	return 0
}

func (m *ResetPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ResetPasswordResponse struct {
	PersonId int64 `protobuf:"varint,1,opt,name=personId" json:"personId,omitempty"`
}

func (m *ResetPasswordResponse) Reset()                    { *m = ResetPasswordResponse{} }
func (m *ResetPasswordResponse) String() string            { return proto1.CompactTextString(m) }
func (*ResetPasswordResponse) ProtoMessage()               {}
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ResetPasswordResponse) GetPersonId() int64 {
	if m != nil {
		return m.PersonId
	}
	return 0
}

func init() {
	proto1.RegisterType((*GetPersonRequest)(nil), "proto.GetPersonRequest")
	proto1.RegisterType((*GetPersonResponse)(nil), "proto.GetPersonResponse")
	proto1.RegisterType((*ResetPasswordRequest)(nil), "proto.ResetPasswordRequest")
	proto1.RegisterType((*ResetPasswordResponse)(nil), "proto.ResetPasswordResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PersonService service

type PersonServiceClient interface {
	GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*GetPersonResponse, error)
}

type personServiceClient struct {
	cc *grpc.ClientConn
}

func NewPersonServiceClient(cc *grpc.ClientConn) PersonServiceClient {
	return &personServiceClient{cc}
}

func (c *personServiceClient) GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*GetPersonResponse, error) {
	out := new(GetPersonResponse)
	err := grpc.Invoke(ctx, "/proto.PersonService/GetPerson", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PersonService service

type PersonServiceServer interface {
	GetPerson(context.Context, *GetPersonRequest) (*GetPersonResponse, error)
}

func RegisterPersonServiceServer(s *grpc.Server, srv PersonServiceServer) {
	s.RegisterService(&_PersonService_serviceDesc, srv)
}

func _PersonService_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PersonService/GetPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServer).GetPerson(ctx, req.(*GetPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PersonService",
	HandlerType: (*PersonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPerson",
			Handler:    _PersonService_GetPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/auth.proto",
}

// Client API for ResetPasswordService service

type ResetPasswordServiceClient interface {
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error)
}

type resetPasswordServiceClient struct {
	cc *grpc.ClientConn
}

func NewResetPasswordServiceClient(cc *grpc.ClientConn) ResetPasswordServiceClient {
	return &resetPasswordServiceClient{cc}
}

func (c *resetPasswordServiceClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error) {
	out := new(ResetPasswordResponse)
	err := grpc.Invoke(ctx, "/proto.ResetPasswordService/ResetPassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ResetPasswordService service

type ResetPasswordServiceServer interface {
	ResetPassword(context.Context, *ResetPasswordRequest) (*ResetPasswordResponse, error)
}

func RegisterResetPasswordServiceServer(s *grpc.Server, srv ResetPasswordServiceServer) {
	s.RegisterService(&_ResetPasswordService_serviceDesc, srv)
}

func _ResetPasswordService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResetPasswordServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ResetPasswordService/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResetPasswordServiceServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResetPasswordService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ResetPasswordService",
	HandlerType: (*ResetPasswordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResetPassword",
			Handler:    _ResetPasswordService_ResetPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/auth.proto",
}

func init() { proto1.RegisterFile("pb/auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x50, 0xcf, 0x4b, 0x80, 0x30,
	0x14, 0xce, 0xa2, 0xc8, 0x57, 0x42, 0x8d, 0x22, 0xb1, 0x0e, 0xb2, 0x53, 0x27, 0x05, 0x85, 0xce,
	0x75, 0x8a, 0xa0, 0x83, 0xad, 0xfe, 0x01, 0x6d, 0x0f, 0x12, 0xca, 0xad, 0xbd, 0x99, 0xff, 0x7e,
	0x30, 0x9b, 0xa8, 0x49, 0x9d, 0xc6, 0xbe, 0x8f, 0xef, 0xc7, 0xfb, 0x20, 0xd2, 0x4d, 0x5e, 0xf7,
	0xf6, 0x2d, 0xd3, 0x46, 0x59, 0xc5, 0xf6, 0xdd, 0xc3, 0x6f, 0xe0, 0xe4, 0x1e, 0x6d, 0x85, 0x86,
	0x54, 0x27, 0xf0, 0xb3, 0x47, 0xb2, 0x8c, 0xc3, 0x31, 0x7e, 0xd4, 0xed, 0xfb, 0x9d, 0x94, 0x06,
	0x89, 0xe2, 0x20, 0x0d, 0xae, 0x43, 0xb1, 0xc0, 0x78, 0x0e, 0xa7, 0x33, 0x1d, 0x69, 0xd5, 0x11,
	0xb2, 0x04, 0x0e, 0xb5, 0x43, 0x1e, 0xa4, 0x13, 0xed, 0x89, 0xe9, 0xcf, 0x5f, 0xe0, 0x4c, 0x20,
	0xa1, 0xad, 0x6a, 0xa2, 0x41, 0x19, 0xe9, 0xc3, 0xfe, 0xd0, 0xb0, 0x14, 0x8e, 0x3a, 0x1c, 0xbc,
	0x22, 0xde, 0x75, 0x3d, 0xe6, 0x10, 0x2f, 0xe1, 0x7c, 0xe5, 0xfa, 0x7f, 0x95, 0xe2, 0x09, 0xa2,
	0xb1, 0xf8, 0x33, 0x9a, 0xaf, 0xf6, 0x15, 0xd9, 0x2d, 0x84, 0xd3, 0x31, 0xec, 0x62, 0x1c, 0x28,
	0x5b, 0xcf, 0x92, 0xc4, 0xbf, 0x89, 0x31, 0x8c, 0xef, 0x14, 0x72, 0x75, 0x9d, 0x77, 0x7e, 0x84,
	0x68, 0x81, 0xb3, 0xcb, 0x1f, 0x93, 0xad, 0x2d, 0x92, 0xab, 0x6d, 0xd2, 0xa7, 0x34, 0x07, 0x8e,
	0x2e, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x23, 0x97, 0xc7, 0xcb, 0x01, 0x00, 0x00,
}
